### ISSUE TITLE
Vector Member type

### ISSUE THREAD

**Issue by ara-bakiev997** [skiflok/s21_containers#6]
Сделать внутриклассовые переопределения типов. Метод определения псевдонимов типов известен как alias-declaration или type-alias. Есть пример в .cpp. ( using value_type = T;)
По алиас есть инфа по следующим ссылкам (https://en.cppreference.com/w/cpp/language/type_alias
https://www.nextptr.com/tutorial/ta1193988140/how-cplusplus-using-or-aliasdeclaration-is-better-than-typedef)

**Comment by skiflok** [comment]
сделал по спецификации в задании

**Comment by skiflok** [comment]
сделал, надо обсудить
